/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as ScanRevisarReceiptIdRouteImport } from './routes/scan.revisar.$receiptId'
import { Route as ScanProcessandoReceiptIdRouteImport } from './routes/scan.processando.$receiptId'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScanRoute,
} as any)
const ScanRevisarReceiptIdRoute = ScanRevisarReceiptIdRouteImport.update({
  id: '/revisar/$receiptId',
  path: '/revisar/$receiptId',
  getParentRoute: () => ScanRoute,
} as any)
const ScanProcessandoReceiptIdRoute =
  ScanProcessandoReceiptIdRouteImport.update({
    id: '/processando/$receiptId',
    path: '/processando/$receiptId',
    getParentRoute: () => ScanRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRoute
  '/receitas': typeof ReceitasRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/': typeof ScanIndexRoute
  '/scan/processando/$receiptId': typeof ScanProcessandoReceiptIdRoute
  '/scan/revisar/$receiptId': typeof ScanRevisarReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRoute
  '/receitas': typeof ReceitasRoute
  '/scan': typeof ScanIndexRoute
  '/scan/processando/$receiptId': typeof ScanProcessandoReceiptIdRoute
  '/scan/revisar/$receiptId': typeof ScanRevisarReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/funcionarios': typeof FuncionariosRoute
  '/receitas': typeof ReceitasRoute
  '/scan': typeof ScanRouteWithChildren
  '/scan/': typeof ScanIndexRoute
  '/scan/processando/$receiptId': typeof ScanProcessandoReceiptIdRoute
  '/scan/revisar/$receiptId': typeof ScanRevisarReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/funcionarios'
    | '/receitas'
    | '/scan'
    | '/scan/'
    | '/scan/processando/$receiptId'
    | '/scan/revisar/$receiptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/funcionarios'
    | '/receitas'
    | '/scan'
    | '/scan/processando/$receiptId'
    | '/scan/revisar/$receiptId'
  id:
    | '__root__'
    | '/'
    | '/funcionarios'
    | '/receitas'
    | '/scan'
    | '/scan/'
    | '/scan/processando/$receiptId'
    | '/scan/revisar/$receiptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FuncionariosRoute: typeof FuncionariosRoute
  ReceitasRoute: typeof ReceitasRoute
  ScanRoute: typeof ScanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/revisar/$receiptId': {
      id: '/scan/revisar/$receiptId'
      path: '/revisar/$receiptId'
      fullPath: '/scan/revisar/$receiptId'
      preLoaderRoute: typeof ScanRevisarReceiptIdRouteImport
      parentRoute: typeof ScanRoute
    }
    '/scan/processando/$receiptId': {
      id: '/scan/processando/$receiptId'
      path: '/processando/$receiptId'
      fullPath: '/scan/processando/$receiptId'
      preLoaderRoute: typeof ScanProcessandoReceiptIdRouteImport
      parentRoute: typeof ScanRoute
    }
  }
}

interface ScanRouteChildren {
  ScanIndexRoute: typeof ScanIndexRoute
  ScanProcessandoReceiptIdRoute: typeof ScanProcessandoReceiptIdRoute
  ScanRevisarReceiptIdRoute: typeof ScanRevisarReceiptIdRoute
}

const ScanRouteChildren: ScanRouteChildren = {
  ScanIndexRoute: ScanIndexRoute,
  ScanProcessandoReceiptIdRoute: ScanProcessandoReceiptIdRoute,
  ScanRevisarReceiptIdRoute: ScanRevisarReceiptIdRoute,
}

const ScanRouteWithChildren = ScanRoute._addFileChildren(ScanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FuncionariosRoute: FuncionariosRoute,
  ReceitasRoute: ReceitasRoute,
  ScanRoute: ScanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
